USE SharedBoard;

CREATE TABLE shared_links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    page_id INT NOT NULL,
    token VARCHAR(64) NOT NULL,
    expires_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT NOT NULL
);
